# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response.proto',
  package='state',
  serialized_pb='\n\x0eresponse.proto\x12\x05state\"S\n\x08Response\x12*\n\x08response\x18\x01 \x02(\x0e\x32\x18.state.Response.Response\"\x1b\n\x08Response\x12\x06\n\x02IN\x10\x00\x12\x07\n\x03OUT\x10\x01')



_RESPONSE_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='state.Response.Response',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=81,
  serialized_end=108,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='state.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='state.Response.response', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_RESPONSE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=108,
)

_RESPONSE.fields_by_name['response'].enum_type = _RESPONSE_RESPONSE
_RESPONSE_RESPONSE.containing_type = _RESPONSE;
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

  # @@protoc_insertion_point(class_scope:state.Response)


# @@protoc_insertion_point(module_scope)
