# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state.proto',
  package='state',
  serialized_pb='\n\x0bstate.proto\x12\x05state\"d\n\x05State\x12)\n\tgameState\x18\x01 \x02(\x0e\x32\x16.state.State.GameState\"0\n\tGameState\x12\x0b\n\x07INITIAL\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\t\n\x05\x45NDED\x10\x02')



_STATE_GAMESTATE = _descriptor.EnumDescriptor(
  name='GameState',
  full_name='state.State.GameState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INITIAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENDED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=74,
  serialized_end=122,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='state.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameState', full_name='state.State.gameState', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATE_GAMESTATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=122,
)

_STATE.fields_by_name['gameState'].enum_type = _STATE_GAMESTATE
_STATE_GAMESTATE.containing_type = _STATE;
DESCRIPTOR.message_types_by_name['State'] = _STATE

class State(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATE

  # @@protoc_insertion_point(class_scope:state.State)


# @@protoc_insertion_point(module_scope)
